CUDA_VISIBLE_DEVICES=4,5 python train.py \
--save_dir ../models/radar2rain-peakyloss-fromscratch/checkpoint \
--gen_frm_dir ../models/radar2rain-peakyloss-fromscratch/gen \
--input_length 10 \
--seq_length 11 \
--img_width 64 \
--img_channel 1 \
--patch_size 4 \
--batch_size 32 \
--lr 0.001 \
--test_interval 1000 \
--snapshot_interval 500 \
--dataset_name rain \
--train_data_paths ../data/rain/list-Z9080 \
--valid_data_paths ../data/radar/list-Z9080 \
--reverse_input False
